import { PropertyListing } from '../types';

export const mockProperties: PropertyListing[] = [
  {
    id: 'prop-1',
    ownerId: 'owner-456',
    title: 'Luxury Sea-Facing Apartment',
    description: 'Breathtaking sea views from this ultra-modern high-rise apartment. Located in the heart of Bandra, this property features premium marble flooring, custom architectural lights, a wrap-around balcony overlooking the ocean, and private elevator access. Gym and infinity pool included in the building amenities.',
    price: 180000,
    address: 'Carter Road, Bandra West',
    city: 'Mumbai',
    bedrooms: 3,
    bathrooms: 3,
    furnishing: 'fully-furnished',
    listingType: 'rent',
    videoUrl: 'https://player.vimeo.com/external/371433846.sd.mp4?s=236da2f3c054f4d823e1e6955a5b512dbf2d9dbd&profile_id=139&oauth2_token_id=57447761',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prop-2',
    ownerId: 'owner-456',
    title: 'Minimalist Penthouse in Worli',
    description: 'Sleek, minimalist lines define this spacious penthouse overlooking the Sea Link. Featuring high ceilings, full-screen glass panes, open kitchen layout with integrated appliances, smart automation features, and a private wooden terrace deck. Perfect for professionals looking for comfort.',
    price: 240000,
    address: 'Worli Sea Face',
    city: 'Mumbai',
    bedrooms: 4,
    bathrooms: 4,
    furnishing: 'semi-furnished',
    listingType: 'rent',
    videoUrl: 'https://player.vimeo.com/external/435674703.sd.mp4?s=7f1645ed35e7dfc998f5c9e2b192801452fa0570&profile_id=165&oauth2_token_id=57447761',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prop-3',
    ownerId: 'owner-789',
    title: 'Chic Studio near Indiranagar',
    description: 'A cozy, premium designed studio loft in a quiet lane near Indiranagar. Extremely efficient storage solutions, floor-to-ceiling bookshelves, study nook, separate walk-in closet, and a private balcony filled with green plants. Just minutes away from top restaurants and workspaces.',
    price: 45000,
    address: 'HAL 2nd Stage, Indiranagar',
    city: 'Bangalore',
    bedrooms: 1,
    bathrooms: 1,
    furnishing: 'fully-furnished',
    listingType: 'rent',
    videoUrl: 'https://player.vimeo.com/external/403848951.sd.mp4?s=d00e70be319d65851d95ee2ad5f6cf67f96b9f29&profile_id=165&oauth2_token_id=57447761',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prop-4',
    ownerId: 'owner-789',
    title: 'Modern 2 BHK Penthouse',
    description: 'Bright and airy luxury penthouse in Koregaon Park. Comes with a spacious private sky-terrace, designer teakwood furniture, modular kitchen setup, dedicated utility room, and backup generator power. Located in a premium gated estate with high security.',
    price: 65000,
    address: 'Lane 7, Koregaon Park',
    city: 'Pune',
    bedrooms: 2,
    bathrooms: 2,
    furnishing: 'fully-furnished',
    listingType: 'rent',
    videoUrl: 'https://player.vimeo.com/external/403848951.sd.mp4?s=d00e70be319d65851d95ee2ad5f6cf67f96b9f29&profile_id=165&oauth2_token_id=57447761',
    thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80',
    createdAt: new Date().toISOString(),
  }
];
